Write-Host 'Manual frontend review guide'
Write-Host ''
Write-Host '- Revisar responsive en desktop, tablet y mobile.'
Write-Host '- Revisar spacing y alineaciones consistentes.'
Write-Host '- Revisar empty states y pantallas sin datos.'
Write-Host '- Revisar mensajes de error y exito.'
Write-Host '- Revisar jerarquia visual de titulos, textos y acciones.'
Write-Host '- Revisar botones visibles, claros y con foco accesible.'
Write-Host '- Revisar consistencia visual entre fondos, modal e historial.'
Write-Host '- Revisar accesibilidad basica: labels, contraste y focus visible.'
