Write-Host 'Manual security review guide'
Write-Host ''
Write-Host '- Revisar secrets, tokens y credenciales en el repo.'
Write-Host '- Revisar validaciones de formularios y reglas del service.'
Write-Host '- Revisar uso de innerHTML, bypassSecurityTrust y HTML crudo.'
Write-Host '- Revisar console.log, console.debug y trazas sobrantes.'
Write-Host '- Revisar any innecesarios o tipado debil.'
Write-Host '- Revisar duplicacion de logica sensible entre UI y negocio.'
Write-Host '- Revisar mensajes de error visibles al usuario.'
Write-Host '- Confirmar typecheck limpio y build funcional.'
